/*Template generated by WebStorm on Monday (5/8/23), 5:32 PM.
 * Author: kramstyles
 * Filename: ColorItem.jsx
 */

import PropTypes from "prop-types";

const ColorItem = ({ color, id, handleClick }) => {
  return (
    <div
      className={`grid-column col-${id}`}
      style={{ backgroundColor: color }}
      onClick={handleClick}
    >
      <h1>{id}</h1>
    </div>
  );
};

ColorItem.propTypes = {
  id: PropTypes.number.isRequired,
  color: PropTypes.string.isRequired,
  handleClick: PropTypes.func.isRequired,
};

export default ColorItem;
