/*Template generated by WebStorm on Monday (5/8/23), 5:31 PM.
 * Author: kramstyles
 * Filename: ColorList.jsx
 */

import { useState } from "react";
import ColorItem from "./ColorItem";
import {colorArray} from "./data";

const ColorList = () => {
  const [colors, setColors] = useState(colorArray);
  return (
    <div className="grid-container">
        {colors.map((color, id) => (
            <ColorItem color={color} id={id + 1} />
        ))}
    </div>
  );
};

export default ColorList;
