/*Template generated by WebStorm on Monday (5/8/23), 5:32 PM.
* Author: kramstyles
* Filename: ColorItem.jsx
*/

import PropTypes from "prop-types";

const ColorItem = ({color, id}) => {
    return (
        <div className={`grid-column col-${id}`} style={{backgroundColor: color}}>
            <h1>{id}</h1>
        </div>
    );
};

ColorItem.propTypes = {
    id: PropTypes.number.isRequired,
    color: PropTypes.string.isRequired
}

export default ColorItem;
